vim.cmd("set termguicolors")
vim.cmd("let g:tokyonight_style = 'night'")
vim.cmd("let g:tokyonight_enable_italic = 1")
vim.cmd("colorscheme tokyonight")
-- vim.cmd('let g:airline_theme = "tokyonight"')
